apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: registryyib2999.azurecr.io/poi:1.0
        imagePullPolicy: IfNotPresent
        name: poi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: secrets-files
            mountPath: /secrets
      volumes:
        - name: secrets-files
          secret:
            secretName: sqlinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: poi
  sessionAffinity: None
  type: ClusterIP