apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
      namespace: web
    spec:
      containers:
      - image: registryyib2999.azurecr.io/tripviewer:1.0
        imagePullPolicy: IfNotPresent
        name: tripviewer
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api.svc.cluster.local"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api.svc.cluster.local"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: BING_MAPS_KEY
          value: "AvnbwNHtO0Zm95Y8eL9ogNUZU1sj6ZO8caNQsnvik4jrfVuqdSXgLynB3dyI1OiR"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0