apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sql
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "teamResources-private-kv"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "38990c71-cb9a-431d-84a7-f8b849c8bc89"
    objects:  |
      array:
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret        
    tenantId: "70cf8c0f-facf-4cc3-9177-63c03dd53c13"