apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
      namespace: default
    spec:
      containers:
      - image: registryyib2999.azurecr.io/trips:1.0
        imagePullPolicy: IfNotPresent
        name: trips
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: trips
  sessionAffinity: None
  type: LoadBalancer